[package]
name = "luminalabsgames/value"
description = "A value container utility for Roblox"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["LuminaLabsGames"]

[dependencies]
Signal = "sleitnick/signal@2.0.3"