[package]
name = "luminalabsgames/characterguidearrow"
description = "Character guide arrow utility for Roblox"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["LuminaLabsGames"]

[dependencies]
