[package]
name = "luminalabsgames/dispatcher"
description = "A dispatcher utility for Roblox"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["LuminaLabsGames"]

[dependencies]
