[package]
name = "luminalabsgames/uistrokeadjuster"
description = "UI stroke adjustment utility for Roblox"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["LuminaLabsGames"]

[dependencies]
